import type { KnowledgeResult } from "@/api/voiceWorkspaces"
import { workspaceErrorMessage } from "./workspaceChatLogic"
import { useLocale } from "@/i18n"

export function WorkspaceKnowledge({ result, sourceNames, onOpen }: { result: KnowledgeResult; sourceNames: Record<string, string>; onOpen: (id: string) => void }) {
  const { t } = useLocale()
  const statusLabel = (status: string | null) => t(status === "not_found" ? "voiceWorkspaceChat.noMatches" : status === "failed" ? "voiceWorkspaceChat.failed" : status === "needs_ocr" ? "voiceWorkspaceChat.readability" : status === "partial" ? "underlag.knowledge.partial" : status === "empty" ? "underlag.status.empty" : "voiceWorkspaceChat.processing")
  return <div className="space-y-4 p-5">{result.items.length ? result.items.map((reference) => <article key={reference.reference_id} className="rounded-xl border border-[color:var(--border-hairline)] bg-white p-4 shadow-sm"><div className="mb-2 flex items-center gap-2"><button type="button" className="grid size-7 shrink-0 place-items-center rounded-full bg-db-gold-200 text-xs font-semibold" aria-label={t("voiceWorkspaceChat.source", { number: reference.number })} onClick={() => onOpen(reference.reference_id)}>{reference.number}</button><h3 className="text-sm font-semibold">{reference.title}</h3></div><p className="whitespace-pre-wrap text-sm leading-relaxed">{reference.excerpt}</p><button type="button" className="mt-3 text-xs font-medium underline decoration-db-gold-400 underline-offset-4" onClick={() => onOpen(reference.reference_id)}>{t("voiceWorkspaceChat.openSource")}</button>{reference.stale ? <p className="mt-2 text-xs text-destructive">{t("voiceWorkspaceChat.stale")}</p> : null}</article>) : <p className="text-sm text-muted-foreground">{t("voiceWorkspaceChat.emptyEvidence")}</p>}{result.gaps.length ? <div className="rounded-xl border border-db-gold-300 bg-db-gold-100 p-4"><h3 className="mb-2 text-sm font-semibold">{t("voiceWorkspaceChat.gaps")}</h3><ul className="list-disc space-y-1 pl-5 text-sm">{result.gaps.map((gap, i) => <li key={i}>{gap.source_id && sourceNames[gap.source_id] ? <strong>{sourceNames[gap.source_id]}: </strong> : null}{statusLabel(gap.status)}{gap.detail ? <> · {workspaceErrorMessage(new Error(gap.detail), t)}</> : null}</li>)}</ul></div> : null}</div>
}
