import { useEffect } from "react"
import { FileText, GitBranch, Layers, Search, X } from "lucide-react"
import type { DocumentKnowledgeAnchor } from "@/api/underlag"
import type { Comparison, KnowledgeResult, Relations, Workspace, WorkspaceArtifact, WorkspaceChart, WorkspaceSelection, WorkspaceState, WorkspaceView } from "@/api/voiceWorkspaces"
import { useLocale } from "@/i18n"
import { WorkspaceArtifactEditor } from "./WorkspaceArtifactEditor"
import { WorkspaceKnowledge } from "./WorkspaceKnowledge"
import { WorkspaceComparison } from "./WorkspaceComparison"
import { WorkspaceChartView } from "./WorkspaceChartView"
import { WorkspaceRelations } from "./WorkspaceRelations"
import { WorkspaceSourcePane } from "./WorkspaceSourcePane"
import { clearWorkspaceDocumentSelection } from "./workspaceDocumentFocus"

export function WorkspaceCanvas({ workspace, knowledge, onState, onOpen, onReady, onError, onSaved, onSearch }: {
  workspace: Workspace; knowledge: KnowledgeResult
  onState: (change: (state: WorkspaceState) => WorkspaceState) => void
  onOpen: (id: string) => void; onReady: (key: string) => void; onError: (key: string, message: string) => void
  onSaved: (artifact: WorkspaceArtifact) => void; onSearch: (query: string) => void
}) {
  const { t } = useLocale()
  const { state } = workspace
  const artifact = workspace.artifacts.find((row) => row.id === state.active_artifact_id)
  const reference = workspace.references.find((row) => row.reference_id === state.selection?.reference_id)
  useEffect(() => { if (artifact?.status === "ready" && ((artifact.kind === "comparison" && state.view === "comparison") || (artifact.kind === "relations" && state.view === "relations") || (state.view === "documents" && artifact.kind === "chart"))) onReady(`artifact:${artifact.id}:${artifact.revision}`) }, [artifact, onReady, state.view])
  useEffect(() => { if (state.view === "evidence") onReady("evidence") }, [knowledge, onReady, state.view])
  const excerptReference = reference?.source_kind !== "underlag" ? reference : undefined
  const selection = (value: WorkspaceSelection) => onState((current) => ({ ...current, selection: { artifact_id: artifact?.id, artifact_revision: artifact?.revision, ...value } }))
  const clearSelection = (sourceId: string) => onState((current) => clearWorkspaceDocumentSelection(current, sourceId, workspace.references))
  const tabs: { id: WorkspaceView; icon: typeof FileText }[] = [{ id: "evidence", icon: Search }, { id: "comparison", icon: Layers }, { id: "documents", icon: FileText }, { id: "relations", icon: GitBranch }]
  const documentIds = state.split_source_ids.length === 2 ? state.split_source_ids : state.documents.slice(0, 1).map((row) => row.source_id)
  return <section className="flex h-full min-h-0 min-w-0 flex-1 flex-col bg-db-ink-50">
    <nav className="flex shrink-0 gap-1 overflow-x-auto border-b border-[color:var(--border-hairline)] bg-white px-3 pt-2" aria-label={t("voiceWorkspaceChat.title")}>{tabs.map(({ id, icon: Icon }) => <button key={id} type="button" aria-current={state.view === id ? "page" : undefined} className={`flex items-center gap-2 whitespace-nowrap border-b-2 px-3 py-3 text-sm ${state.view === id ? "border-db-gold-500 font-semibold" : "border-transparent text-muted-foreground hover:text-db-ink-950"}`} onClick={() => onState((current) => ({ ...current, view: id }))}><Icon size={15} />{t(`voiceWorkspaceChat.${id}`)}</button>)}</nav>
    {state.view === "evidence" ? <div className="min-h-0 flex-1 overflow-auto"><form className="m-5 flex rounded-lg border bg-white px-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const query = String(form.get("query") ?? "").trim(); if (query) onSearch(query) }}><input name="query" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" placeholder={t("voiceWorkspaceChat.searchPlaceholder")} aria-label={t("voiceWorkspaceChat.search")} /><button type="submit" aria-label={t("voiceWorkspaceChat.search")}><Search size={18} /></button></form><WorkspaceKnowledge result={knowledge} sourceNames={Object.fromEntries(workspace.sources.map((source) => [source.id, source.filename]))} onOpen={onOpen} /></div> : null}
    {state.view === "comparison" ? artifact?.kind === "comparison" && artifact.status === "ready" ? <WorkspaceComparison comparison={artifact.content as Comparison} references={workspace.references} onOpen={onOpen} /> : <p className="p-6 text-sm text-muted-foreground">{t("voiceWorkspaceChat.emptyComparison")}</p> : null}
    {state.view === "relations" ? artifact?.kind === "relations" && artifact.status === "ready" ? <WorkspaceRelations relations={artifact.content as Relations} references={workspace.references} selection={state.selection} onSelect={selection} onOpen={onOpen} /> : <p className="p-6 text-sm text-muted-foreground">{t("voiceWorkspaceChat.emptyRelations")}</p> : null}
    {state.view === "documents" ? <>
      <div className="flex shrink-0 items-center gap-1 overflow-x-auto border-b bg-white px-2 py-2">{state.documents.map((document) => <span key={document.source_id} className="flex items-center rounded-lg border bg-db-ink-50 text-xs"><button type="button" className="max-w-44 truncate px-3 py-2" onClick={() => onState((current) => ({ ...current, active_artifact_id: null, split_source_ids: [], documents: [document, ...current.documents.filter((row) => row.source_id !== document.source_id)] }))}>{workspace.sources.find((row) => row.id === document.source_id)?.filename ?? workspace.references.find((row) => row.source_id === document.source_id)?.title}</button><button type="button" className="pr-2" aria-label={t("voiceWorkspaceChat.closeDocument")} onClick={() => onState((current) => ({ ...current, documents: current.documents.filter((row) => row.source_id !== document.source_id), split_source_ids: [] }))}><X size={12} /></button></span>)}{state.documents.length >= 2 ? <button type="button" className="ml-auto whitespace-nowrap rounded border px-3 py-2 text-xs" onClick={() => onState((current) => ({ ...current, active_artifact_id: null, split_source_ids: current.split_source_ids.length === 2 ? [] : current.documents.slice(0, 2).map((row) => row.source_id) }))}>{t(state.split_source_ids.length === 2 ? "voiceWorkspaceChat.single" : "voiceWorkspaceChat.split")}</button> : null}</div>
      <div className="flex min-h-0 flex-1 overflow-hidden">{excerptReference && !state.active_artifact_id ? <WorkspaceSourcePane workspace={workspace} sourceId={excerptReference.source_id} page={1} zoom={1} reference={excerptReference} onNavigate={() => undefined} onSelection={(anchor) => selection({ reference_id: excerptReference.reference_id, anchor })} onClearSelection={() => clearSelection(excerptReference.source_id)} onReady={() => onReady(`source:${excerptReference.source_id}:${excerptReference.reference_id}`)} onError={(_, message) => onError(`source:${excerptReference.source_id}:${excerptReference.reference_id}`, message)} /> : artifact?.kind === "document" && artifact.status === "ready" ? <div className="min-w-0 flex-1"><WorkspaceArtifactEditor key={artifact.id} workspaceId={workspace.id} artifact={artifact} references={workspace.references} onSaved={onSaved} onReady={(revision) => onReady(`artifact:${artifact.id}:${revision}`)} onSelect={(block_id, revision) => selection({ block_id: block_id ?? undefined, artifact_revision: revision })} onOpen={onOpen} /></div> : artifact?.kind === "chart" && artifact.status === "ready" ? <div className="min-w-0 flex-1 overflow-auto"><WorkspaceChartView chart={artifact.content as WorkspaceChart} references={workspace.references} onOpen={onOpen} /></div> : documentIds.length ? documentIds.map((sourceId) => { const document = state.documents.find((row) => row.source_id === sourceId); if (!document) return null; const documentReference = (reference?.source_id === sourceId ? reference : undefined) ?? workspace.references.find((row) => row.reference_id === document.reference_id); return <WorkspaceSourcePane key={sourceId} workspace={workspace} sourceId={sourceId} page={document.page} zoom={document.zoom} reference={documentReference} onNavigate={(page, zoom) => onState((current) => ({ ...current, documents: current.documents.map((row) => row.source_id === sourceId ? { ...row, page, zoom, reference_id: documentReference?.anchor?.page_number && page !== documentReference.anchor.page_number ? null : row.reference_id } : row), selection: reference?.source_id === sourceId && reference.anchor?.page_number && page !== reference.anchor.page_number ? null : current.selection }))} onSelection={(anchor: DocumentKnowledgeAnchor) => selection({ source_id: sourceId, anchor })} onClearSelection={() => clearSelection(sourceId)} onReady={() => onReady(`source:${sourceId}:${documentReference?.reference_id ?? ""}`)} onError={(_, message) => onError(`source:${sourceId}:${documentReference?.reference_id ?? ""}`, message)} /> }) : <p className="p-6 text-sm text-muted-foreground">{t("voiceWorkspaceChat.emptyDocuments")}</p>}</div>
    </> : null}
  </section>
}
