"""Knowledge layer: read API plus ingest. Isolated from panel / research-router / MCP."""

from app.services.knowledge.canonical_ingest import ingest_extracted_source
from app.services.knowledge.chunking import KnowledgeChunker, text_unit_to_chunk
from app.services.knowledge.claims import (
    ANSWERED_BY,
    SUPPORTED_BY,
    KnowledgeClaim,
    KnowledgeClaimAnswerHit,
    KnowledgeClaimError,
    answer_research_need,
    claim_answers_for_question_key,
    claims_answering_question_key,
    persist_knowledge_claim,
    persist_knowledge_claims,
    supersede_knowledge_claim,
    supporting_text_unit_ids_for_quote,
)
from app.services.knowledge.embeddings import (
    EmbeddingProvider,
    EmbeddingSpec,
    OpenAIEmbeddingProvider,
)
from app.services.knowledge.entities import (
    KnowledgeEntity,
    KnowledgeEntityError,
    knowledge_entity,
    knowledge_entity_id,
    persist_knowledge_entities,
    persist_knowledge_entity,
)
from app.services.knowledge.events import (
    CLAIM_ADDED,
    CLAIM_SUPERSEDED,
    EDGE_ADDED,
    GRAPH_EVENT_TYPES,
    KnowledgeGraphEvent,
    list_graph_events,
    record_graph_event,
)
from app.services.knowledge.extractors import (
    DefaultTextExtractor,
    ExtractedBlock,
    ExtractedDocument,
    TextExtractor,
)
from app.services.knowledge.ingest import KnowledgeIngestResult, KnowledgeIngestService
from app.services.knowledge.models import (
    EmbeddedKnowledgeChunk,
    EmbeddedKnowledgeQuery,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeHit,
    KnowledgeQuery,
    KnowledgeScope,
    KnowledgeScopeRequiredError,
)
from app.services.knowledge.persistence import (
    get_canonical_document_by_identity,
    get_current_document_version,
    list_document_versions,
    persist_segmented_document,
)
from app.services.knowledge.provider import (
    SUPABASE_PROVIDER_ID,
    KnowledgeError,
    KnowledgeNotFoundError,
    KnowledgeProvider,
    KnowledgeProviderNotFoundError,
    KnowledgeVectorStoreError,
)
from app.services.knowledge.registry import (
    KnowledgeProviderRegistry,
    build_knowledge_registry,
)
from app.services.knowledge.relationships import (
    ABOUT,
    CONTRADICTS,
    CORE_RELATIONS,
    PART_OF,
    SAME_AS,
    KnowledgeRelationship,
    KnowledgeRelationshipError,
    knowledge_relationship,
    persist_knowledge_relationship,
    persist_knowledge_relationships,
    relationships_touching,
    require_relation,
)
from app.services.knowledge.segmentation import DocumentSegmenter, expand_text_unit_context
from app.services.knowledge.supabase_provider import SupabaseKnowledgeProvider
from app.services.knowledge.units import (
    CanonicalDocument,
    DocumentSection,
    DocumentVersion,
    SegmentedDocument,
    TextUnit,
    make_document_version_id,
    make_section_id,
    make_text_unit_id,
)
from app.services.knowledge.vector_store import (
    KnowledgeVectorStore,
    MemoryKnowledgeVectorStore,
    SupabaseVectorBucketStore,
    TextUnitEmbeddingReader,
    VectorBucketClient,
)

__all__ = [
    "ABOUT",
    "ANSWERED_BY",
    "CLAIM_ADDED",
    "CLAIM_SUPERSEDED",
    "CONTRADICTS",
    "CORE_RELATIONS",
    "EDGE_ADDED",
    "GRAPH_EVENT_TYPES",
    "PART_OF",
    "SAME_AS",
    "SUPABASE_PROVIDER_ID",
    "SUPPORTED_BY",
    "CanonicalDocument",
    "DefaultTextExtractor",
    "DocumentSection",
    "DocumentSegmenter",
    "DocumentVersion",
    "EmbeddedKnowledgeChunk",
    "EmbeddedKnowledgeQuery",
    "EmbeddingProvider",
    "EmbeddingSpec",
    "ExtractedBlock",
    "ExtractedDocument",
    "KnowledgeChunk",
    "KnowledgeChunker",
    "KnowledgeClaim",
    "KnowledgeClaimAnswerHit",
    "KnowledgeClaimError",
    "KnowledgeDocument",
    "KnowledgeEntity",
    "KnowledgeEntityError",
    "KnowledgeError",
    "KnowledgeGraphEvent",
    "KnowledgeHit",
    "KnowledgeIngestResult",
    "KnowledgeIngestService",
    "KnowledgeNotFoundError",
    "KnowledgeProvider",
    "KnowledgeProviderNotFoundError",
    "KnowledgeProviderRegistry",
    "KnowledgeQuery",
    "KnowledgeRelationship",
    "KnowledgeRelationshipError",
    "KnowledgeScope",
    "KnowledgeScopeRequiredError",
    "KnowledgeVectorStore",
    "KnowledgeVectorStoreError",
    "MemoryKnowledgeVectorStore",
    "OpenAIEmbeddingProvider",
    "SegmentedDocument",
    "SupabaseKnowledgeProvider",
    "SupabaseVectorBucketStore",
    "TextExtractor",
    "TextUnit",
    "TextUnitEmbeddingReader",
    "VectorBucketClient",
    "answer_research_need",
    "build_knowledge_registry",
    "claim_answers_for_question_key",
    "claims_answering_question_key",
    "expand_text_unit_context",
    "get_canonical_document_by_identity",
    "get_current_document_version",
    "ingest_extracted_source",
    "knowledge_entity",
    "knowledge_entity_id",
    "knowledge_relationship",
    "list_document_versions",
    "list_graph_events",
    "make_document_version_id",
    "make_section_id",
    "make_text_unit_id",
    "persist_knowledge_claim",
    "persist_knowledge_claims",
    "persist_knowledge_entities",
    "persist_knowledge_entity",
    "persist_knowledge_relationship",
    "persist_knowledge_relationships",
    "persist_segmented_document",
    "record_graph_event",
    "relationships_touching",
    "require_relation",
    "supersede_knowledge_claim",
    "supporting_text_unit_ids_for_quote",
    "text_unit_to_chunk",
]
